### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by lfarah** [panghaijiao/HJDanmakuDemo#10]
Hey, your library is really interesting.

The only problem I found was the ```README.md```, which lacks information.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to do it.

What are your thoughts?

**Comment by lfarah** [comment]
https://github.com/vsouza/awesome-ios/issues/1335

**Comment by smallqiang** [comment]
不知道用户ID有什么用呢，我现在是通过播放视频来显示弹幕的，有个功能是可以关闭不显示弹幕，然后可以再开启弹幕，这个我用stop和resume可以实现了。但是还有一个需求就是当关闭弹幕的时候，自己发的弹幕要显示，不知道可以怎样实现呢？如果可以通过ID来过滤掉那就好了。
