### ISSUE TITLE
如何设置弹幕关闭但可显示自己发送的弹幕。

### ISSUE THREAD

**Issue by smallqiang** [panghaijiao/HJDanmakuDemo#11]
不知道用户ID有什么用呢，我现在是通过播放视频来显示弹幕的，有个功能是可以关闭不显示弹幕，然后可以再开启弹幕，这个我用stop和resume可以实现了。但是还有一个需求就是当关闭弹幕的时候，自己发的弹幕要显示，不知道可以怎样实现呢？如果可以通过ID来过滤掉那就好了。

**Comment by panghaijiao** [comment]
HJDanmaku 2.0 was released
