### ISSUE TITLE
请问，如果HJDanmakuConfiguration的numberOfLines很小，弹幕重叠的解决方案

### ISSUE THREAD

**Issue by gechanghang** [panghaijiao/HJDanmakuDemo#14]
其实不算bug，
如果numberOfLines将设为1，连续调用sendDanmaku:方法，弹幕会重叠在一起。如果我不想重叠在一起，请问有什么好办法吗？
![qq20171122-152922](https://user-images.githubusercontent.com/7567814/33114951-1cba846a-cf9a-11e7-8175-51476acd5219.png)

**Comment by panghaijiao** [comment]
- (void)sendDanmaku:(HJDanmakuModel *)danmaku forceRender:(BOOL)force;  里面有个force参数，控制要不要强制显示的，设置为NO就可以了

**Comment by panghaijiao** [comment]
/* send customization. when force, renderer will draw the danmaku immediately and ignore the maximum quantity limit.
   you should call -sendDanmakus: instead of -sendDanmaku:forceRender: to send the danmakus from a remote servers
 */

**Comment by gechanghang** [comment]
解决了！
