### ISSUE TITLE
关于_renderQueue的疑问

### ISSUE THREAD

**Issue by wning13** [panghaijiao/HJDanmakuDemo#22]
您好，首先感谢开源。有一个问题请教一下：
`dispatch_set_target_queue(_renderQueue, dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0));
`
这行代码的目的是什么？
按我的理解这样会导致render的时候是并行执行的，可能会出现重叠

**Comment by panghaijiao** [comment]
DISPATCH_QUEUE_SERIAL 这个是一个串行队列，线程安全的

**Comment by wning13** [comment]
感谢解答，很抱歉，是我理解错了，我之前以为target_queue是一个并行队列的时候会变成并行
