### ISSUE TITLE
锁的问题  弹幕碰撞

### ISSUE THREAD

**Issue by chaningcheng** [panghaijiao/HJDanmakuDemo#25]
1.  OSSpinLock 是不安全的并且是已经被废弃的建议替换

2. 如果比较快速的频繁调用 [self.danmakuView sendDanmaku:danmakuModel forceRender:YES]; 会出现弹幕叠加在一起的

**Comment by panghaijiao** [comment]
1、OSSpinLock在高并发下的确会出现问题，可以考虑替换
2、第二个问题，forceRender:YES表示强制渲染，忽略弹幕是否碰撞，主要应用在发送端本地显示场景，如果是其它人发送的弹幕，可以将forceRender设置为NO
