### ISSUE TITLE
谢谢你 开源的 框架

### ISSUE THREAD

**Issue by hi363138911** [panghaijiao/HJDanmakuDemo#5]
DanmakuBaseModel  这个class 下方法过期了 - -。

    self.size = CGSizeMake([self.text sizeWithFont:[UIFont systemFontOfSize:self.textSize]].width, paintHeight);
///可以修改
    self.size =CGSizeMake([self.text sizeWithAttributes:@{ NSFontAttributeName : [UIFont systemFontOfSize:self.textSize] }].width, paintHeight) ;

感谢你的开源 框架

**Comment by panghaijiao** [comment]
恩，谢谢提醒，因为这个库支持最低版本比较低，所以没有使用新的接口，当然，如果你们工程项目支持版本高一点可以使用新接口

**Comment by hi363138911** [comment]
了解  - -
